version: '3'

services:
  dns:
    image: mgood/resolvable:latest
    container_name: dns
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/resolv.conf:/tmp/resolv.conf

  devui:
    build: devui
    container_name: devui
    ports:
      - 80:80
  
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=qwerty7"
      - "MYSQL_DATABASE=sonar"
      - "MYSQL_USER=sonar"
      - "MYSQL_PASSWORD=sonar"

  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - "jenkins_data:/var/jenkins_home"
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m \
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.rmi.port=9090 \
        -Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.port=9090 \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.local.only=false \
        -Djava.rmi.server.hostname=10.100.10.12 \
        -Djenkins.security.FrameOptionsPageDecorator.enabled=false"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "./influxdb/config:/etc/influxdb"
      - "influx_data:/var/lib/influxdb"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - ./telegraf/config:/etc/telegraf

  jmxtrans:
    image: jmxtrans/jmxtrans:latest
    depends_on:
      - influxdb
      - jenkins
    environment:
      - "SECONDS_BETWEEN_RUNS=5"
      - "JMXTRANS_OPTS=-Dhost=10.100.10.12 -Dport=9090 -Dalias=jenkins -Dinfluxuser=root -Dinfluxpassword=root -Dinfluxdb=telegraf -Dinfluxurl=http://influxdb:8086"
    volumes:
      - ./jmxtrans/config:/var/lib/jmxtrans

  sonar:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      - "SONARQUBE_JDBC_USERNAME=sonar"
      - "SONARQUBE_JDBC_PASSWORD=sonar"
      - "SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
      
volumes:
    jenkins_data:
    influx_data:
    mysql-data:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins: