version: '3'

services:
  dns:
    image: mgood/resolvable:latest
    container_name: dns
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/resolv.conf:/tmp/resolv.conf
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.1
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600