version: '3'

services:
  consul:
      image: consul:0.8.1
      container_name: consul
      command: agent -server -bootstrap -client 0.0.0.0 -ui
      ports:
        - "8500:8500"
        - "8400:8400"
        - "8600:8600"
      labels:
        - "SERVICE_TAGS=consul"
      volumes:
        - ./consul/config:/consul/config

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    network_mode: "host"
    command: "consul://consul:8500"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    network_mode: "host"
    depends_on:
      - consul

  dns:
    image: mgood/resolvable:latest
    container_name: dns
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/resolv.conf:/tmp/resolv.conf

  jenkins:
    image: jenkins:latest
    container_name: jenkins
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - "JAVA_OPTS=-Xms512m -Xmx512m \
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.rmi.port=9090 \
        -Dcom.sun.management.jmxremote=true \
        -Dcom.sun.management.jmxremote.port=9090 \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.local.only=false \
        -Djava.rmi.server.hostname=10.100.10.12"

  sonar:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - "9000:9000"
      - "9092:9092"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "./influxdb/config:/etc/influxdb"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - ./telegraf/config:/etc/telegraf

  jmxtrans:
    image: jmxtrans/jmxtrans:latest
    depends_on:
      - influxdb
      - jenkins
    environment:
      - "SECONDS_BETWEEN_RUNS=5"
      - "JMXTRANS_OPTS=-Dhost=10.100.10.12 -Dport=9090 -Dalias=jenkins -Dinfluxuser=root -Dinfluxpassword=root -Dinfluxdb=telegraf -Dinfluxurl=http://influxdb:8086"
    volumes:
      - ./jmxtrans/config:/var/lib/jmxtrans

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    container_name: elasticsearch
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      
